### ISSUE TITLE
Vue Vine requirements todo list

### ISSUE THREAD

**Issue by ShenQingchuan** [vue-vine/vue-vine#75]
We'll list all todo tasks of Vue Vine here, both short-term and medium to long-term.

> ## 💡 Current high priority
>
>

## Features
- [x] SSR target compilation. Thanks to @wzc520pyfm https://github.com/vue-vine/vue-vine/pull/139
- [x] External CSS file import. Requested from https://github.com/vue-vine/vue-vine/issues/151

## Docs, Information and guidance
- [x] Vue Vine compilation playground / REPL - https://github.com/vue-vine/repl
- [ ] Clear and detailed contribution guide

## Extension features
- [x] Intellisense component name when typing '<' in template #52 , Thanks to @johnsoncodehk 
- [x] Integrate Vue Volar features for component props intellisense #53 , Thanks to @johnsoncodehk 
- [x] Vue Vine Extension needs to provide some useful quick snippets, handled in #125  Thanks to @wzc520pyfm

## CLI features
- [x] Publish `create-vue-vine` CLI tool for project starter template #67 , may need help from @so1ve 

## Lint & Format
- [x] Build auto format actions in ESLint.   ~( Compatible with [ESLint Stylistic](https://eslint.style/) )~
- [x] Integrate with Stylelint & Prettier (for template)

## Ecosystem
- [x] Vue Router Integration and real-case example #81 
- [x] Nuxt module #133 Thanks to @wzc520pyfm 

## CI & Actions
- [ ] Automatic publish scripts by Github Action
- [ ] More robust test CI process and more detailed report

**Comment by ShenQingchuan** [comment]
Almost all major tasks are already completed for now.

So I temporarily close this issue.
